### ISSUE TITLE
Inviting non-UCSB collaborators to a repository

### ISSUE THREAD

**Issue by aisichenko** [ucsb/github-guide#9]
Hello, I have created a team under the ucsb organization for my research group. We have some collaborations with another university and we are wondering if we can allow external collaborators to access these repositories.

Thanks!

**Comment by jwoods-ucsb** [comment]
hello @aisichenko you should be able to add external collaborators. You need to know their existing github.com userid.

**Comment by kevinwucodes** [comment]
@aisichenko you can invite outside collaborators to individual repositories.  Check out this guide https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/adding-outside-collaborators-to-repositories-in-your-organization for more information.

However, you cannot add an outside collaborator to a team with the UCSB organization.  This is because when adding a user to a team to the UCSB organization, they become full members and thus need to be added to our Identity Provider.
